<?php
/**
 * @file
 * Code for the Teaser Quote feature.
 */

include_once 'teaser_quote.features.inc';

/**
 * Implements hook_teaser_types().
 */
function teaser_quote_teaser_types() {
  return array(
    'teaser_quote' => 1,
  );
}

/**
 * Implements hook_preprocess_node().
 */
function teaser_quote_preprocess_node(&$variables, $hook) {
  if ($variables['type'] == 'teaser_quote') {

    // check if there is a link to use on wrapper
    if (empty($variables['field_teaser_link'])) {
      $variables['classes_array'][] = 'no-wrapper-link';
    }

    // Add the external link here so it can be used in the tpl
    $node = node_load($variables['nid']);
    $link = field_get_items('node', $node, 'field_teaser_link');
    if (isset($link['0']['url'])) {
      $variables['wrapper_link'] = $link['0']['url'];
    }
  }
}