<?php
/**
 * @file
 * Code for the Teaser Facebook feature.
 */

include_once 'teaser_facebook.features.inc';

/**
 * Implements hook_teaser_types().
 */
function teaser_facebook_teaser_types() {
  return array(
    'teaser_facebook' => 1,
  );
}

/**
 * Implements hook_field_formatter_info().
 */
function teaser_facebook_field_formatter_info() {
  return array(
    'teaser_facebook_likebox' => array(
      'label' => t('Facebook likebox'),
      'field types' => array('text'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function teaser_facebook_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'teaser_facebook_likebox':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#markup' => teaser_facebook_likebox_render($item['value']),
        );
      }
      $element['#attached']['js'][] = drupal_get_path('module', 'teaser_facebook') . '/teaser_facebook.field.js';
      break;
  }

  return $element;
}

/**
 * Render a facebook likebox widget.
 *
 * @todo Dynamic height, which currently not supported by Facebook.
 */
function teaser_facebook_likebox_render($page) {
  $url = 'https://www.facebook.com/' . $page;
  return <<<EOF
<div class="fb-page" data-href="$url" data-width="500" data-height="449" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="false" data-show-posts="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="$url"><a href="$url">Facebook</a></blockquote></div></div>
EOF;
}
